name: CI/CD Release
on:
  push:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic.outputs.new_release_version }}
      released: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits
            semantic-release-slack-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  build:
    needs: release
    if: needs.release.outputs.released == 'true'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: v${{ needs.release.outputs.new_version }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Native Package
        run: ./gradlew jpackage
        shell: bash

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.new_version }}
          files: build/jpackage/*.{exe,dmg,deb}
